# Generated by Django 4.2.9 on 2024-01-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
